### PR TITLE
Create test_consumer.py

### PR DESCRIPTION
**Pull request by ChadDa3mon**
Hopefully a simpler sort of 'hello world' for unit testing for python novices like me.

# Description

I had a hard time trying to make sense of your documentation (still not sure where/how to edit your primary documentation) so after getting some basic unit tests to work I wanted to offer up this in hopes it may help other 'novices' like me. 

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [X] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [X] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [X] My changes do not generate any new warnings
- [X] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by Lancetnik** [comment]
One of the biggest FastStream features is an automatic pydantic-base serialization, described [there](https://faststream.airt.ai/0.2/getting-started/subscription/annotation/).

So, your example has no sense, cuz it represents incorrect framework usage

Btw, looks like you just missed "Tutorial" documentation section and looked only at "Kafka" one. All Framework features are described detail enough there. If you have some problems with the specific section/page, you can just click to "edit" btn on the rite top of a documentation page, edit it and create a PR.

**Comment by ChadDa3mon** [comment]
Thanks for the feedback, this is your guys project so I have to assume you know better than I do. 

I'd just like to say that in my setting (Working for a large enterprise) and having created a half-dozen kafka consumers now for various projects, I don't think your assumptions are accurate. 

In these cases I'm simply looking to consume a message from a topic, and I have no idea what shape/form that payload will take (some other system publishes it). In this example, the json payload is a giant mess (100+ lines and 3 different levels of structure). I literally need 3 fields out of this whole thing. 

There's no need to create a model for this, I just pull out the 3 fields I need, validate that data, and move on with acting upon the message I got. No need to make this any more complicated than that. 

None of the existing tutorials or examples had a clear cut example of how you could do that so I figured I'd try to give back in case any other noobs like me are trying this out :)

**Comment by davorrunje** [comment]
@ChadDa3mon I see your point. Let me think a bit about where and how exactly to add such an example over the weekend.

**Comment by Lancetnik** [comment]
@ChadDa3mon is it the example you were tried to implement by yourself?

```python
from faststream import FastStream
from faststream.kafka import KafkaBroker

broker = KafkaBroker()
app = FastStream(broker)

@broker.subscriber("test")
async def handle(name: str, age: int):
    print(f"{name=}, {age=}")

@app.after_startup
async def t():
    await broker.publish({
        "name": "John",
        "age": 25,
        "useless": {
            "nested": "useless"
        }
    }, topic="test")
```

If you need no to consume all fields, you can just define the fields you want: all other will be ignored

**Pull request closed without merging**
