### PR TITLE
1129 - Create a publish command for the CLI

### LINKED ISSUE #1129: Feature: CLI publish command
User should be able to publish a test message right from the command line smth like this

```bash
faststream publish main:app message topic
```

Probably, all arguments after `main:app` can be interpreted as `broker.publish(*args)` and all `--topic=topicname` options can be interpreted as `broker.publish(**kwargs)`. Also, it should supports `--rpc` flag with systemout output to be suitable as a healthcheck container command.

### PR DESCRIPTION
**Pull request by MRLab12**
# Description

Users should be able to publish a test message right from the command line. To do this, a `publish` command has been added to the CLI `main.py` file. 

Close  #1129

## How to Test

To test the new publish functionality introduced in this Pull Request, follow these steps:

1. **Start Your FastStream Application**: First, you need to have a running FastStream application. You can start your application with the following command, assuming your FastStream application is defined in a file named `testfaststreamapp.py`:

    ```bash
    python testfaststreamapp.py
    ```

    Make sure your FastStream application is set up to subscribe to a channel named `input_channel` and publishes processed messages to another channel (e.g., `output_channel`). Here's a simple example of what your `testfaststreamapp.py` might contain:

    ```python
    from faststream import FastStream
    from faststream.redis import RedisBroker

    broker = RedisBroker("redis://localhost:6379")
    app = FastStream(broker=broker)

    @broker.subscriber(channel="input_channel")
    @broker.publisher(channel="output_channel")
    async def process_message(message: str) -> str:
        print(f"Received message: {message}")
        return f"Processed: {message}"

    if __name__ == "__main__":
        app.run()
    ```

2. **Send a Test Message**: With your FastStream application running, you can send a test message using the `faststream publish` command. Use the following command to publish a message to the `input_channel`:

    ```bash
    faststream publish testfaststreamapp:app "Hello World" --channel "input_channel" --rpc
    ```

## Type of change

- [x] New feature (a non-breaking change that adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by MRLab12** [comment]
Having issues running tests locally. They seem to get stuck and the test run never finishes. 

Opened this draft PR to get eyes on the work and get feedback on whether the changes here fulfill the requirements of adding this feature.

**Comment by MRLab12** [comment]
Hey @davorrunje , this PR is in Draft because I wanted to check I had the correct logic and if the code changes are doing the intended changes. I haven't looked into the tests yet, will check.

If it looks good to be reviewed, I can mark it ready. Would also be helpful if you can recommend next steps for documenting and other checks before having this PR ready to be deployed.

**Comment by davorrunje** [comment]
@MRLab12 can you please give me write access to your repo, I would like to push some changes to you branch

**Comment by MRLab12** [comment]
@davorrunje Sent you invite for access.

**Comment by davorrunje** [comment]
@MRLab12 The tests are failing for Python versions 3.8 and 3.9. Can you please check locally with the following command:
```
bash scripts/test.sh -m "(slow and (not nats and not kafka and not confluent and not rabbit and not redis)) or (not nats and not kafka and not confluent and not rabbit and not redis)"
```
I think your tests are interfering with the rest. Can you please check the way you handle async code and compare it with the `run` function and its tests?

**Comment by MRLab12** [comment]
@davorrunje Hey I was really busy with interviews and did not have a chance to take a look a this. I was able to find that adding `@pytest.mark.asyncio` to the tests seems to properly end the event loop. It is a weird to use it this way since the test are not using `async`, but the `publish` command is. Let me know if this works or we should handle tests some other way.

**Review by davorrunje — APPROVED** [review]

**Comment by davorrunje** [comment]
@MRLab12 Thanx for the PR, I am merging it now :)

**Pull request merged**
