### PR TITLE
feat: ASGI support

### LINKED ISSUE #1181: Feature: add K8S probes checker API
We should provides users with an ability to check application health in a some way. It can be reached by using multiple mechanism, so we can create a base `Checker` Protocol and use it the following way

```python
app = FastStream(broker)
app.add_checker(
     SocketChecker("/sock"),
     # HTTPChecker(port=8000),
     # ...
)
```

And check all of them by the same command

```shell
faststream probe main:app
```

So, we can create multiple checkers for various cases and user can implement any checker by itself in the same time

* [x] add `broker.ping()` unified method
* [ ] add `BaseCheker` using `broker.ping()`
* [ ] implement `HTTPChecker` (inheritor of `BaseCheker`)
* [ ] add CLI command to use any checker

### LINKED ISSUE #1638: Fix: need to speed up testing for confluent
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
Slow running tests for confluent

**Describe the solution you'd like**
Significantly speed up test execution.

### LINKED ISSUE #1647: Feature: RabbitMQ add support for fail_fast param
Currently the RabbitMQ broker is based on a RobustConnection from aio-pika.

The options available with the broker although plenty are missing a few important ones. One of the is "fail_fast" param. This param allows you to start your code even if RabbitMQ is down, else it will fail after a timeout.

Example of using this with aio-pika

```python
connection = RobustConnection(RABBITMQ_URL, fail_fast="False")
await connection.connect()
```

Yes, the param is a `string`. Probably makes sense to make it a Boolean on `faststream` side. By default `fail_fast` is enabled.

### PR DESCRIPTION
**Pull request by Lancetnik**
# Description

It just a minimal **ASGI** support to make **FastStream** able to serve **ASGI** endpoints and be runned by **uvicorn** or any other server.

Implementation is very limited and was created to provides users with a basic functional for metrics, documentation, readi- and liveness probes hosting.

```python
from faststream.nats import NatsBroker
from faststream.asgi import AsgiFastStream, make_ping_asgi

from prometheus_client import make_asgi_app
from prometheus_client.registry import CollectorRegistry

broker = NatsBroker()

prometheus_registry = CollectorRegistry()

app = AsgiFastStream(
    broker,
    asyncapi_path="/docs",
    asgi_routes=[
        ("/health", make_ping_asgi(broker, timeout=5.0)),
        ("/metrics", make_asgi_app(registry=prometheus_registry))
    ]
)
```

```shell
uvicorn main:app
```

Close #1181, close #1638, close #1647

## Type of change

Please delete options that are not relevant.

- [x] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [x] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [x] I have ensured that static analysis tests are passing by running `scripts/static-analysis.sh`
- [x] I have included code examples to illustrate the modifications

### CODE REVIEW

**Review by kumaranvpl — DISMISSED** [review]

**Comment by Lancetnik** [comment]
@kumaranvpl did you read `[ASGI](getting-started/asgi.md)` page?

**Comment by kumaranvpl** [comment]
@Lancetnik I didn't. I will do it later today.

**Comment by Lancetnik** [comment]
> @Lancetnik I didn't. I will do it later today.
Appreciate a lot!

**Comment by Lancetnik** [comment]
I just can't make confluent working without local testing 😢

**Comment by kumaranvpl** [comment]
> I just can't make confluent working without local testing 😢

@Lancetnik Do you want me to take a look?

Checkout my docs changes here - https://github.com/airtai/faststream/pull/1635/commits/8e64d6f228662d1a2ed5edd2ed9ecd5487cf73c9

**Comment by Lancetnik** [comment]
> @Lancetnik Do you want me to take a look?

If you have time for it. Or just guide me, please

**Comment by Lancetnik** [comment]
@kumaranvpl I found the problem, don't care

**Comment by Lancetnik** [comment]
Nope, I have no idea again... Can we just remove confluent?

**Review by kumaranvpl — APPROVED** [review]

**Pull request merged**
