### PR TITLE
feat: add application states

### PR DESCRIPTION
**Pull request by Artem-Safronov**
# Description

Hello. While writing the test for launching the application, I encountered the need to check the application's active state. I suggest adding two states for the application: "stopped" and "running".

## Type of change

Please delete options that are not relevant.

- [ ] New feature (a non-breaking change that adds functionality)

## Checklist

- [ ] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [ ] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [ ] My changes do not generate any new warnings
- [ ] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-analysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by Artem-Safronov** [comment]
@Lancetnik 
Hello, will there be an opportunity to take a look? I would like to understand whether it’s worth waiting for the states or if I should consider approaching this case differently.

**Comment by Lancetnik** [comment]
> @Lancetnik Hello, will there be an opportunity to take a look? I would like to understand whether it’s worth waiting for the states or if I should consider approaching this case differently.

Oh, sorry, missed that one
Unfortunately, we can't merge it to main until 0.6 release. It is in the final stage (mypy and docs polishing) and a don't wont to add new features to main. If you want - you can add this feature to 0.6 branch. It has already some kind of state for application, so it should be easy to add.

**Comment by Artem-Safronov** [comment]
> > @Lancetnik Hello, will there be an opportunity to take a look? I would like to understand whether it’s worth waiting for the states or if I should consider approaching this case differently.
> 
> Oh, sorry, missed that one Unfortunately, we can't merge it to main until 0.6 release. It is in the final stage (mypy and docs polishing) and a don't wont to add new features to main. If you want - you can add this feature to 0.6 branch. It has already some kind of state for application, so it should be easy to add.

I changed the pull request to 0.0.6. I see that the StartAbleApplication class has its own state, but it relates to dependency injection. I suggest considering renaming it to _di_state.

**Comment by Lancetnik** [comment]
@Artem-Safronov I designed this state is a single state for the app, so we should extend it by your functional instead of renaming

**Comment by Lancetnik** [comment]
> is an instance of the DIState class

It is not a problem, we can add special `ApplicationState`, providing `di_state` and application-specific states as well

**Review by Lancetnik — APPROVED** [review]

**Pull request merged**
