### PR TITLE
Fix multiple docs issues

### LINKED ISSUE #1684: Bug: Mkdocs Material edit icon doesnt work in Public Api section.
**Describe the bug**
If you try to click edit icon in Public Api section of docs it will redirect you to not valid url.

**How to reproduce**
Go to https://faststream.airt.ai/latest/public_api/faststream/BaseMiddleware/
Try to click on 
image

**Expected behavior**
Goes to docs/docs/en/api/...

**Observed behavior**
Goes to docs/docs/en/public_api/... (not valid)

This problem comes from this issue: https://github.com/mkdocs/mkdocs/issues/1974
One of faststream contributors solved it making public_api/ redirect to api/ (His issue is mentioned in the higher issue and in these lines)
https://github.com/airtai/faststream/blob/f2d617870346078a6891fa3cb3657b242291250b/docs/create_api_docs.py#L289-L290

This problem leads to another issue - https://github.com/airtai/faststream/issues/1438. 
Link Checker action isn't able to check this links and fails (not only because of this links but including them)

### PR DESCRIPTION
**Pull request by kumaranvpl**
# Description

- [x] As mentioned in issue https://github.com/airtai/faststream/issues/1684#issue-2464742759, the edit button in `public_api` points to a wrong url in github. This is because `public_api` is a symlink to `api` directory and github does not do automatic redirection for symlinks. To fix this, I have used [mkdocs hooks](https://www.mkdocs.org/user-guide/configuration/#hooks) feature, and wrote a new hook function `on_page_markdown` in `create_api_docs.py`.
- [x] Fix broken codeql svg badge
- [x] Update `--max-response-body-size` to prevent failures in check docs links workflow
- [x] Fix wrong path in `docs_deploy.yaml`
- [x] Remove a mention of faststream-gen
- [x] Fix formatting of `EmailStr` in api summary
- [x] Rename twitter.com to x.com to prevent redirection which consumes bit more time in CI

Fixes #1684, #1438

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [ ] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [ ] My changes do not generate any new warnings
- [ ] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-analysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Review by Lancetnik — APPROVED** [review]

**Comment by Lancetnik** [comment]
@kumaranvpl please, check, that all our CI jobs have the same file extension "yaml/yaml" everywhere

And mark closing by the PR issues

**Comment by kumaranvpl** [comment]
> @kumaranvpl please, check, that all our CI jobs have the same file extension "yaml/yaml" everywhere
> 
> And mark closing by the PR issues

Okay I will check. PR is not ready for merging yet.

**Comment by Lancetnik** [comment]
Btw what do you think about "docs/api" directory removing as a first step of create_docs_api script? It should help with removed classes/files hanging in References. Now I make this operation manually.

**Comment by kumaranvpl** [comment]
> Btw what do you think about "docs/api" directory removing as a first step of create_docs_api script? It should help with removed classes/files hanging in References. Now I make this operation manually.

Then I believe it will take too much time to build the docs. Is that okay?

**Comment by Lancetnik** [comment]
> Then I believe it will take too much time to build the docs. Is that okay? 

If we are building it only to deploy - it is okay. But, I don't sure about time difference. In my estimation it is about 1-2 seconds difference only

**Pull request merged**
