### PR TITLE
fix: patch broker within testbroker context only

### LINKED ISSUE #1479: Bug: starting the broker breaks in-memory behaviour
**Describe the bug**
I'm not really sure if this is a bug or not. If it's not a bug but an intended behaviour, then I suppose it should be at least mentioned in the docs.

Right now, if you start the broker and then try to patch it with the in-memory broker for testing purposes, call count assertions will fail (at least when testing a publisher).

It may seem obvious to someone, but I've spent quite some time trying to figure out the problem. Connecting a broker before running tests didn't seem like the problem: what if I wish to run tests both in-memory and with a real thing, so why not making a connection beforehand?

**How to reproduce**
Consider this example code:

```python
from collections.abc import AsyncIterator

import pytest
from dishka import Provider, provide, Scope, AsyncContainer, make_async_container
from faststream.rabbit import TestRabbitBroker, RabbitBroker
from faststream.rabbit.publisher.asyncapi import AsyncAPIPublisher


class RabbitProvider(Provider):
    @provide(scope=Scope.APP)
    async def broker(self) -> AsyncIterator[RabbitBroker]:
        dsn = "amqp://guest:guest@0.0.0.0:5672/"
        broker = RabbitBroker(url=dsn)

        await broker.start()
        yield broker
        await broker.close()

    @provide(scope=Scope.APP)
    async def publisher(self, broker: RabbitBroker) -> AsyncAPIPublisher:
        return broker.publisher()


@pytest.fixture
async def container() -> AsyncIterator[AsyncContainer]:
    container = make_async_container(RabbitProvider())
    yield container
    await container.close()


async def test_publisher(container: AsyncContainer):
    broker = await container.get(RabbitBroker)
    publisher = await container.get(AsyncAPIPublisher)

    async with TestRabbitBroker(broker):
        for i in range(10):
            await publisher.publish(f"message {i}")

        assert publisher.mock.call_count == 10
```

Running this test would lead to `AssertionError: assert 0 == 10`. However, if you remove `await broker.start()` call from the broker provider method, it works fine.

**Expected behavior**
In-memory broker works even if the broker has established the connection.

**Observed behavior**
In-memory broker doesn't register `publish` calls if it has established the connection before patching.

**Environment**
`Running FastStream 0.5.7 with CPython 3.12.0 on Darwin`

### PR DESCRIPTION
**Pull request by sfran96**
# Description

When using a pre-started broker, the broker gets patched only within the context manager, and once it exists the previous connection is still usable.

```python
import pytest

from faststream.rabbit import TestRabbitBroker, RabbitBroker


@pytest.mark.asyncio
async def test_fix():
    broker = RabbitBroker(url="amqp://guest:guest@0.0.0.0:5672/")
    await broker.start()
    publisher = broker.publisher()

    async with TestRabbitBroker(broker):
        for i in range(10):
            await publisher.publish(f"message {i}")

        assert publisher.mock.call_count == 10

    assert getattr(publisher, "mock", None) is None
    await publisher.publish(f"message 11")

```

Fixes #1479

Some of the other changes in the PR are related to using the pre-commit hooks, or not all tests working in < py3.10.

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples, or any documentation updates)
- [x] Bug fix (a non-breaking change that resolves an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [ ] This change requires a documentation update

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [x] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [x] I have ensured that static analysis tests are passing by running `scripts/static-analysis.sh`
- [x] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by Lancetnik** [comment]
Seems like some tests are broken now due new changes

**Comment by sfran96** [comment]
I saw now, something with patching one of the functions incorrectly. I also added more tests for the `with_real` option as per my understanding of the use of the flag.

**Comment by sfran96** [comment]
Some tests were, weirdly, still failing. I've checked the subscriber handlers for NATS and Redis and both seem to create multiple listeners for the same queue/topic if `broker.start()` is called multiple times 🤔.

I'm guessing this is not intended behavior, because it doesn't seem to happen on the Kafka or Rabbit brokers.

I can't seem to get the confluent kafka broker with test `test_broker_with_real_patches_subscribers_and_subscribers`, I'm a bit puzzled. 

### Redis

```python
from faststream.redis import RedisBroker

broker = RedisBroker()
queue = "test_queue"


async def main():
    event1 = asyncio.Event()
    event2 = asyncio.Event()

    @broker.subscriber(queue)
    async def m(msg):
        if event1.is_set():
            event2.set()
        else:
            event1.set()

    await broker.start()
    await broker.start()
    await broker.publish("hello", queue)

    await asyncio.wait(
        (
            asyncio.create_task(event1.wait()),
            asyncio.create_task(event2.wait()),
        ),
        timeout=1,
    )

    assert event1.is_set() and event2.is_set() is False


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())

```

### NATS

```python
from faststream.nats import NatsBroker

broker = NatsBroker()
queue = "test_queue"


async def main():
    event1 = asyncio.Event()
    event2 = asyncio.Event()

    @broker.subscriber(queue)
    async def m(msg):
        if event1.is_set():
            event2.set()
        else:
            event1.set()

    await broker.start()
    await broker.start()
    await broker.publish("hello", queue)

    await asyncio.wait(
        (
            asyncio.create_task(event1.wait()),
            asyncio.create_task(event2.wait()),
        ),
        timeout=1,
    )

    assert event1.is_set() and event2.is_set() is False


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

I'm pushing the changes and you can evaluate if this is the intended behavior, or event just to decide to move it to another PR.

**Comment by Lancetnik** [comment]
@sfran96 broker wasn't designed for multiple `start` calls. Of course, we should refactor whole TestBroker behavior and I am planning this to 0.6.0. But can we make smth right here, without big changes?

**Review by Lancetnik — APPROVED** [review]

**Comment by Lancetnik** [comment]
Seems like we can merge it already, tu

**Review by Lancetnik — DISMISSED** [review]

**Review by Lancetnik — APPROVED** [review]

**Pull request merged**
