### PR TITLE
test with 3.12 added to CI

### PR DESCRIPTION
**Pull request by davorrunje**
# Description

Please include a summary of the change and specify which issue is being addressed. Additionally, provide relevant motivation and context.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (a non-breaking change that adds functionality)

## Checklist

- [ ] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [ ] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [ ] My changes do not generate any new warnings
- [ ] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by Jaroslav2001** [comment]
Maybe add an optional `uvloop` dependency?
So far this library does not support python 3.12

https://github.com/MagicStack/uvloop/issues/567

**Comment by davorrunje** [comment]
> Maybe add an optional `uvloop` dependency? So far this library does not support python 3.12
> 
> [MagicStack/uvloop#567](https://github.com/MagicStack/uvloop/issues/567)

Merged #798 and a new version released:

https://github.com/airtai/faststream/releases/tag/0.2.1

**Comment by Lancetnik** [comment]
We need to wait aiokafka 3.12 support: https://github.com/aio-libs/aiokafka/issues/928

**Comment by Lancetnik** [comment]
Well, aiokafka supports 3.12 now
https://github.com/aio-libs/aiokafka/releases/tag/v0.9.0

**Comment by davorrunje** [comment]
Already working on it, we’ll be finished tonight

**Pull request closed without merging**
