### PR TITLE
Introducing FastStream Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [FastStream Guru](https://gurubase.io/g/faststream) to Gurubase. FastStream Guru uses the data from this repo and data from the [docs](https://faststream.airt.ai/latest/) to answer questions by leveraging the LLM.

In this PR, I showcased the "FastStream Guru", which highlights that FastStream now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable FastStream Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by Lancetnik** [comment]
@kursataktas wow, it's fantastic! Thank you a lot! I was thinking about adding LLM assistant to documentation even today!

But, can we please add the badge not README only, but to the docs as well - https://github.com/airtai/faststream/blob/main/docs/docs/en/faststream.md

Also, I have some additional questions:
1) can we integrate requests to **Gurubase** right from site documentation search?
Smth like [**NATS** does](https://docs.nats.io/running-a-nats-service/introduction/installation)
2) Has **Gurubase** any Github integration for Issues / Discussions first-line help?

Also, I have to ask @davorrunje about his thoughts 😄

**Review by davorrunje — APPROVED** [review]
Great work! Thanx ❤️

**Comment by davorrunje** [comment]
@kursataktas this is great! I'll test it over the weekend. Thank you again :)

**Comment by kursataktas** [comment]
Hi everyone,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by Lancetnik** [comment]
@kursataktas thank you for such great project! I am enjoying by it and waiting for a new features 😃

**Comment by Lancetnik** [comment]
Btw, how can I get access to Gurubase Admin panel? I logged in by Github, but didn't see any "My gurus"
> You haven't been granted access to any gurus yet.

**Comment by kursataktas** [comment]
> Btw, how can I get access to Gurubase Admin panel? I logged in by Github, but didn't see any "My gurus"
> 
> > You haven't been granted access to any gurus yet.

Normally, you should claim FastStream Guru as explained [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). However, since I know you are one of the maintainers of FastStream, I have assigned it to your Gurubase account. You should be able to see it now. Please let me know if you need any help, either here or on our [Discord Channel](https://discord.gg/9CMRSQPqx6).

**Comment by kursataktas** [comment]
Hello Everyone,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by Lancetnik** [comment]
> Hello Everyone,
> 
> We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.
> 
> The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).
> 
> You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.
> 

Hi! Yeah, I saw the discord channel announce! Looks great, I plan to play with it locally a bit and then release. Thank you for such awesome project and presonal notification😅

**Pull request merged**
