### PR TITLE
feat: add oauth support

### LINKED ISSUE #1631: Feature: add sasl_oauthbearer support
Hi!

Faststream doesn't allow to authenticate with Oauth. According to [librdkafka/CONFIGURATION.md](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md) `sasl.mechanism` must be set to `OAUTHBEARER`. However this value will get overwritten when specifying it in config and providing it during broker creation. To be precise it will get overwritten by one of `_parse_*` functions in `faststream\confluent\security.py` depending on which security class from `faststream\security.py` will be chosen. Changes should allow broker configuration with oauth:

```
broker = KafkaBroker(
    "host:port",
    config=config,
    security=SASLOAuthBearer(use_ssl=True),
)
```

To achieve this we need to implement a new security class and new parser. I have already created fork with these changes and successfully deployed it.

### PR DESCRIPTION
**Pull request by filip-danieluk**
# Description

Please include a summary of the change and specify which issue is being addressed. Additionally, provide relevant motivation and context.

Fixes #1631

## Type of change

- [x] New feature (a non-breaking change that adds functionality)

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-analysis.sh`
- [ ] I have included code examples to illustrate the modifications

### CODE REVIEW

**Comment by filip-danieluk** [comment]
Hi @Lancetnik, I intend to do that however atm I struggle running test suite at all, `pytest -m 'confluent` results in a segmentation fault on my machine. Same behaviour when I cloned clean faststream repo without my changes. Does that ring any bells? It's 6th or 7th test in order that fails in this way.

**Comment by Lancetnik** [comment]
> Hi @Lancetnik, I intend to do that however atm I struggle running test suite at all, `pytest -m 'confluent'` results in a segmentation fault on my machine. Same behaviour when I cloned clean faststream repo without my changes. Does that ring any bells? It's 6th or 7th test in order that fails in this way.

It is an old confluent Issue (I just can't run on macos) and I can't run confluent tests locally as well. But you do not need run them in your case, just add and check AsyncAPI test for confluent

**Comment by filip-danieluk** [comment]
Got it, on another note. It was already pointed out in #1608 that there is this snippet:
```
  if sasl_mechanism:
      self.config.update(
          {
              "sasl.mechanism": sasl_mechanism,
              "sasl.username": sasl_plain_username,
              "sasl.password": sasl_plain_password,
          }
     )
```
in `client.py` that will cause a warning that user and password are not needed while using Oauthbearer. I could work on a fix for this as well if needed.

**Comment by Lancetnik** [comment]
> Got it, on another note. It was already pointed out in #1608 that there is this snippet:
> 
> ```
>   if sasl_mechanism:
>       self.config.update(
>           {
>               "sasl.mechanism": sasl_mechanism,
>               "sasl.username": sasl_plain_username,
>               "sasl.password": sasl_plain_password,
>           }
>      )
> ```
> 
> in `client.py` that will cause a warning that user and password are not needed while using Oauthbearer. I could work on a fix for this as well if needed.

It will be great

**Comment by filip-danieluk** [comment]
Added test where you asked, by accident added one more in `tests/brokers/confluent`. For that `client.py` code I did bare minimum to get rid of warning. Is there anything else I should do?

**Review by Lancetnik — CHANGES_REQUESTED** [review]
Thank you a lot! But I have to ask you for one more thing. You added `doc/docs_src` example, but didn't include it to the doc. Can you please use it the documentation (here https://github.com/airtai/faststream/blob/main/docs/docs/en/kafka/security.md) and write a test for it here: https://github.com/airtai/faststream/blob/main/tests/docs/kafka/test_security.py ?

**Comment by filip-danieluk** [comment]
`kafka/` or `confluent/` ?

**Comment by Lancetnik** [comment]
> `kafka/` or `confluent/` ?

Sorry, the confluent one

**Comment by filip-danieluk** [comment]
I have added docs to `docs\docs\en\confluent\security.md` however I believe that confluent equivalent of the test you mentioned `https://github.com/airtai/faststream/blob/main/tests/docs/kafka/test_security.py` is actually the test I have already added here `tests/brokers/confluent/test_security.py`, right?

**Comment by Lancetnik** [comment]
> I have added docs to `docs\docs\en\confluent\security.md` however I believe that confluent equivalent of the test you mentioned `https://github.com/airtai/faststream/blob/main/tests/docs/kafka/test_security.py` is actually the test I have already added here `tests/brokers/confluent/test_security.py`, right?

`tests/docs` is more important than regular ones due they covers both `faststream/` and `docs/` code. They can duplicates each other, but documentation tests are required.

**Review by Lancetnik — APPROVED** [review]

**Comment by Lancetnik** [comment]
@filip-danieluk sorry, but why you set security AsyncAPI as `{"type": "oauthBearer"}`? - there is no such type in [AsyncAPI specification](https://v2.asyncapi.com/docs/reference/specification/v2.6.0#securitySchemeObject)

Снимок экрана 2024-09-20 в 14 17 24

Can I ask you to selected correct type from the supporting ones? We faced with a problem now #1802

**Pull request merged**
