### PR TITLE
585 complete kafka part of faststream docs

### LINKED ISSUE #585: Complete Kafka part of faststream docs

### PR DESCRIPTION
**Pull request by Sternakt**
# Description

Please include a summary of the change and specify which issue is being addressed. Additionally, provide relevant motivation and context.

Fixes #585 

## Type of change

Please delete options that are not relevant.

- [x] Documentation (typos, code examples, or any documentation updates)

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [x] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [x] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [x] I have included code examples to illustrate the modifications

### CODE REVIEW

**Review by Lancetnik — COMMENTED** [review]
Can you add `test_me.py` to pytest run?

**Comment by Sternakt** [comment]
> Can you add `test_me.py` to pytest run?

Renamed the examples in docs_src from test_me.py to example.py and referenced in tests folder

**Comment by Lancetnik** [comment]
But why we are running the same test twice for now?

**Comment by Sternakt** [comment]
> But why we are running the same test twice for now?

My mistake, referenced the wrong one in one of the tests

One test is for the example where we use the general `publish` of the `FastStream` and another is when we first create a publisher object and then use its `publish` method

Fixed it :)

**Review by Lancetnik — APPROVED** [review]

**Pull request merged**
